minor fixes

diff --git a/auto-upgrade-dependencies.yml b/auto-upgrade-dependencies.yml
--- a/auto-upgrade-dependencies.yml
+++ b/auto-upgrade-dependencies.yml
@@ -25,8 +25,10 @@ on:
         required: false
         default: 'dependencies, actions, bot'
 
-jjobs:
+jobs:
   setup:
+    env:
+      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
     outputs:
       yarn-cache-dir: ${{ steps.prerequisites.outputs.yarn_cache_dir }}
       cache-key: ${{ steps.fill-yarn-cache.outputs.cache_key }}
@@ -35,13 +37,14 @@ jjobs:
       - id: prerequisites
         name: Prerequisites
         run: |
+          [[ -z "$NPM_TOKEN" ]] && { echo "::error::NPM_TOKEN not set!"; exit 1; } || echo "NPM_TOKEN detected..."
           echo "::set-output name=yarn_cache_dir::$(yarn cache dir)"
           echo "::set-output name=dependencies::$(echo '${{ github.event.inputs.dependencies-to-update }}' | sort | jq -r 'join(" ")')"
 
       - id: fill-yarn-cache
         name: Fill yarn cache
         run: |
-          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc &&
+          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc &&
           echo "yarn add ${{ steps.prerequisites.outputs.dependencies }} --ignore-scripts" &&
           yarn add ${{ steps.prerequisites.outputs.dependencies }} --ignore-scripts && rm .npmrc
           cache_key="${{ runner.os }}-yarn-cache-$(jq -r '.dependencies | to_entries | sort | [.[][]] | join("_")' package.json | sed "s/[^a-zA-Z0-9]/_/g")"
@@ -61,6 +64,7 @@ jjobs:
     env:
       GITHUB_USER: ${{ github.actor }}
       GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
     runs-on: ubuntu-latest
     needs: setup
     permissions:
@@ -80,10 +84,12 @@ jjobs:
       - id: config
         name: NPM token and git config
         run: |
+          [[ -z "$NPM_TOKEN" ]] && { echo "::error::NPM_TOKEN not set!"; exit 1; } || echo "NPM_TOKEN detected..."
+          [[ -z "$GITHUB_TOKEN" ]] && { echo "::error::NPM_TOKEN not set!"; exit 1; } || echo "GITHUB_TOKEN detected..."
           echo '${{ toJson(github.event.inputs) }}'
           git config user.name github-actions
           git config user.email github-actions@github.com
-          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
+          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
           DEFAULT_BRANCH=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
           echo "default_branch=$DEFAULT_BRANCH" >> $GITHUB_ENV
           echo "default_branch_ref=refs/heads/$DEFAULT_BRANCH" >> $GITHUB_ENV
@@ -165,7 +171,7 @@ jjobs:
       - id: dry-run
         name: Dry-run announcement
         if: steps.changes-check.outcome == 'success' && github.event.inputs.dry-run == 'true'
-        run: echo "::warning::Workflow started as dry-run. Not pushing to upstream and skipping PR creation!"
+        run: echo "::warning::Outdated dependencies detected, but workflow started as dry-run. Not pushing to upstream and skipping PR creation!"
 
       - id: push
         name: Commit, push upstream
